# Generated by Django 5.2.9 on 2026-01-01 19:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name_en", models.CharField(max_length=120)),
                ("name_ar", models.CharField(max_length=120)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sku",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("clothes", "Clothes"), ("shoes", "Shoes")],
                        max_length=16,
                    ),
                ),
                ("name_en", models.CharField(max_length=160)),
                ("name_ar", models.CharField(max_length=160)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_ar", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("badge_en", models.CharField(blank=True, max_length=40, null=True)),
                ("badge_ar", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
